version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tienda_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password

  web_django:
    image: tienda-app  # Usamos la imagen que ya construimos
    command: gunicorn Tienda.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_NAME: tienda_db
      DB_USER: postgres
      DB_PASSWORD: secret_password
      DB_HOST: db
      DB_PORT: 5432

  [cite_start]pagos_flask: # El Microservicio (v2) EL ESTRANGULADOR [cite: 88]
    [cite_start]build: ./microservicio_pagos [cite: 89]
    ports:
      - [cite_start]"5000:5000" # Para pruebas iniciales [cite: 91]
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - [cite_start]"80:80" [cite: 94]
    volumes:
      - [cite_start]./nginx/nginx.conf:/etc/nginx/conf.d/default.conf [cite: 96]
    depends_on:
      - [cite_start]web_django [cite: 98]
      - [cite_start]pagos_flask [cite: 99]

volumes:
  postgres_data: