# Generated by Django 5.1.6 on 2026-02-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.CharField(default='Anonimo', max_length=100),
        ),
    ]
